version: '3.3'

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    volumes:
      - 'postgres_db:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    env_file:
      - '.env'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'db'
    ports:
      - '3000:3000'
    volumes:
      - '.:/file-storage'
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      - RAILS_ENV=development
    entrypoint: ./entrypoints/app_entrypoint.sh

  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - 'db'
    volumes:
      - '.:/file-storage'
      - gem_cache:/usr/local/bundle/gems
    env_file: .env.test
    environment:
      - RAILS_ENV=test
      - DATABASE_HOST=db
    entrypoint: ./entrypoints/test_entrypoint.sh

volumes:
  postgres_db:
  gem_cache:
