version: '3.3'

services:
  db:
    container_name: postgres_db
    image: postgres:latest
    volumes:
      - 'postgres_db:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    env_file:
      - '.env'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'db'
      - 'redis'
    ports:
      - '3000:3000'
    volumes:
      - '.:/file-storage'
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      - RAILS_ENV=development
    entrypoint: ./entrypoints/app_entrypoint.sh

volumes:
  redis:
  postgres_db:
  gem_cache:
